name: bookalo
description: A  Flutter project.
version: 1.0.0+1



dependencies:
  paging: ^0.1.0
  groovin_material_icons: ^1.1.6
  flutter:
  
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  share: ^0.6.0+1 
  flutter_range_slider: ^1.1.0
  autocomplete_textfield: ^1.6.4  
  geolocator: ^3.0.1
  flutter_map: ^0.5.0
  flutter_tags: ^0.2.2
  json_annotation: ^2.0.0  
  english_words: ^3.1.5
  geo: ^0.2.0
  material_design_icons_flutter: 3.2.3595
  url_launcher: ^5.0.2
  lipsum: ^1.0.0+1
  flutter_rating: ^0.0.2
  video_player: ^0.10.0+5
  firebase_auth: ^0.8.4+2
  google_sign_in: ^4.0.1+3
  firebase_core: ^0.3.4
  flutter_facebook_login: ^2.0.0
  flutter_twitter_login: ^1.1.0
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_driver:
    sdk: flutter
  screenshots: ^0.1.6
  test: ^1.5.1
  faker: ^1.0.1
  
flutter:
  uses-material-design: true
  assets:
    - locale/i18n_en.json
    - locale/i18n_es.json  
    - assets/images/

flutter_icons:
  image_path: "assets/images/bookalo_icon.png" 
  #adaptive_icon_background: "#e91e63"
  #adaptive_icon_foreground: "assets/images/bookalo_icon_adaptative.png"
  android: true 

